export enum TipoRol {
    SUPERADMIN="SUPERADMIN",
    ADMIN="ADMIN",
    CLIENTE="CLIENTE",
    JEFEZONA="JEFEZONA",
    REMISION="REMISION",
    USUARIO="USUARIO",
    SYSTEM="SYSTEM",
    PLANIFICADOR="PLANIFICADOR",
    DESPACHADOR="DESPACHADOR",
    TRANSPORTASOCIEDAD="TRANSPORTASOCIEDAD",
    CONTROLACCESO="CONTROL ACCESO",
    BASCULA="BASCULA",
    CLIENTELOGISTICA="CLIENTE LOGISTICA"

}